### ISSUE TITLE
After inserting data in table, I have to close table tab and open it again to see data change

### ISSUE THREAD

**Issue by RjPatil27** [slashbaseide/slashbase#113]
Using MySQL, 
Whenever I insert new data into the table, I have to close the tab (open the table tab) and then see the data change. 
Another solution would be to add a refresh button over a tab, after clicking it data in the table gets updated automatically no need to close the tab and open it again.

**Comment by codezuma** [comment]
@paraswaykole  can I work on this thing.

**Comment by paraswaykole** [comment]
Yes! Assigning it to you.
