### ISSUE TITLE
Error when creating a new DB connection (MySQL)

### ISSUE THREAD

**Issue by dr-coton** [slashbaseide/slashbase#128]
Hello. 
I'm getting an error when creating a new DB connection. 
My suspicion is that the error occurs if there is an exclamation point at the end of the password. 

Thank you for creating such a great project.

**Comment by paraswaykole** [comment]
Thanks @dr-coton! Can you tell what type of database connection are you using?

**Comment by dr-coton** [comment]
I connected with Mysql and it worked fine when I changed the password.

**Comment by dr-coton** [comment]
@paraswaykole 
I've done a bunch of tests and it doesn't seem to be the problem I mentioned above. 
I created mysql, mariadb, etc with docker and when I tried to connect to them, I got an error. 
When I tested both Desktop and Web, there seems to be a lot of mysql errors. 
I'll fork the project as much as I can and see where the issue is coming from.

**Comment by paraswaykole** [comment]
Thanks @dr-coton! Please add new issues if you find new bugs / errors in MySQL.

**Comment by dr-coton** [comment]
@paraswaykole 

I found the cause. 

In the file `pkg/queryengines/mysqlqueryengine/queryengine.go`, an error occurred in `MySQL TestConnection`. 

I don't know the exact reason, but it doesn't work while comparing the `test` variable with `1`. 

Since the role of the function in `MySQL TestConnection` is to test the connection, I changed the code to check for the presence or absence of a value rather than validating the exact value. 

I am not a golang expert, so I will not send a separate PR. 
But please review this positively. 

### AS-IS
```go
func (mqe *MysqlQueryEngine) TestConnection(dbConn *models.DBConnection, config *models.QueryConfig) error {
	query := "SELECT 1 AS test;"
	data, err := mqe.RunQuery(dbConn, query, config)
	if err != nil {
		return err
	}
	test := data["rows"].([]map[string]interface{})[0]["0"].(int64)
	if test == 1 {
		return nil
	}
	return errors.New("connection test failed")
}
```

### TO-BE
```go
func (mqe *MysqlQueryEngine) TestConnection(dbConn *models.DBConnection, config *models.QueryConfig) error {
	query := "SELECT 1 AS test;"
	data, err := mqe.RunQuery(dbConn, query, config)
	if err != nil {
		return err
	}
	rows := data["rows"].([]map[string]interface{})
	if len(rows) != 0 {
		return nil
	}
	return errors.New("connection test failed")
}
```

Thanks

**Comment by dr-coton** [comment]
PR : https://github.com/slashbaseide/slashbase/pull/129
