### ISSUE TITLE
for mac_app_chip, couldn't create a new query tab

### ISSUE THREAD

**Issue by Lucas-MorningStar** [slashbaseide/slashbase#137]

**Comment by paraswaykole** [comment]
@Lucas-MorningStar could you please provide more description, thanks!

**Comment by Lucas-MorningStar** [comment]
i created a new connect for mysql , test connection successfully, then i wanted to create a new query tab. Clicked the  'create query' button , there is no response

**Comment by ixre** [comment]
you can download old version like v0.9.2 to work

https://github.com/slashbaseide/slashbase/releases/tag/v0.9.2

**Comment by paraswaykole** [comment]
ab0626cdbbf7087d4ef78e8b5735cecec6b84498 commit will fix this issue. thanks for reporting!
