### ISSUE TITLE
Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

### ISSUE THREAD

**Issue by navicstein** [slashbaseide/slashbase#35]
Downloading the binary file without Docker & running gives an error

```sh
❯ slashbase
Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
```

mostly because the release binaries has an [indirect dependency](https://github.com/slashbaseide/slashbase/blob/main/go.mod#L43) on `go-sqlite3` which in turn needs to be built with CGO

### Steps to reproduce
1) download slashbase binary from [release](https://github.com/slashbaseide/slashbase/releases) page (linux_amd64.zip)
2) add slashbase to path or move to `~/.local/bin`
3) run slashbase & see the error 

### Possible fix
Add 'CGO_ENABLED=1' to go build release command

**Comment by paraswaykole** [comment]
Updated the binary release file for linux_amd64. The new file should work.

Thanks for pointing the issue @navicstein
