### ISSUE TITLE
ID Sequence for Postgresql not being updated when adding items from UI

### ISSUE THREAD

**Issue by Animesh-Ghosh** [slashbaseide/slashbase#41]
I was trying slashbase out after installing `postgresql` and creating a `posts` database with the following schema:
```sql
CREATE TABLE posts (id BIGSERIAL PRIMARY KEY, title TEXT, content TEXT);
```

When I added a tuple in the table via the slashbase UI, I expected the `id` field to be updated automatically.
![image](https://user-images.githubusercontent.com/34956994/210058705-c1cb2941-6503-403a-99c7-9a00dc34b6d0.png)

However the UI showed the value for the `id` column as `NULL`.
![image](https://user-images.githubusercontent.com/34956994/210058726-81d12a20-53af-4a8d-ab9c-24f1e2920bd1.png)

Even though it showed the `id` field with the correct value within the slashbase CLI.
![image](https://user-images.githubusercontent.com/34956994/210058747-f1e1a0cf-f3d5-4506-8557-94c23731b8ec.png)

Note that I had to reload the page (in my case I clicked the the project name on the sidebar to reload the data) to get the correct result to show on the slashbase UI:
![image](https://user-images.githubusercontent.com/34956994/210058755-be470044-fb4d-45ed-87bd-8910ad516811.png)

Maybe we could give an option to the Users to specify which columns need to be returned after doing the `INSERT`s? Not sure if this might cover columns with default values specified too.

**Comment by paraswaykole** [comment]
Commit c280da784bf77c5f97d28818167a2776cfacbca1 closes this issue.
