### ISSUE TITLE
Wishlist: Please add MySQL support

### ISSUE THREAD

**Issue by knutov** [slashbaseide/slashbase#47]
Please add MySQL support. 

Should not be hard to implement, and it's more used worldwide than PostgreSQL

**Comment by paraswaykole** [comment]
Got it. Noted. It is in our roadmap.

**Comment by paraswaykole** [comment]
this is in progress at branch: [feat/mysql-query-engine](/slashbaseide/slashbase/tree/feat/mysql-query-engine)

**Comment by paraswaykole** [comment]
@knutov MySQL support was added in v0.5.0
