### ISSUE TITLE
Unable to connect to MongoDB if password has special characters.

### ISSUE THREAD

**Issue by prashantkhandelwal** [slashbaseide/slashbase#56]
Unable to connect to MongoDB if there are special characters in the password.

For example: I was connecting to the database I have in Azure VM with a password which has '@' in it. The connection was failing as the special character has to be converted into Hexadecimal ASCII i.e. '@' will convert to '%40'. After this change, I was able to connect to the database.

I have made changes in this [commit](https://github.com/prashantkhandelwal/slashbase/commit/430a73a7ca85654175af486be5ee1c5efd4f5f00). @paraswaykole  you can take a look and if all these changes seems okay, then I can raise a PR for this or if there is some other better way of doing this.

**Comment by paraswaykole** [comment]
Is it because of submitting HTML form doing that?

**Comment by prashantkhandelwal** [comment]
> 

I don't think it is due to HTML form. I have a password which has '@' in it and while debugging I am seeing it is passed as it is to the backed function. So UI is not making changes to the data being sent. 

Therefore, I made change to the backend API code so that if someone plans to make use of the API, then this should no occur.

**Comment by paraswaykole** [comment]
Got it! Please send a PR.

**Comment by prashantkhandelwal** [comment]
PR raised - https://github.com/slashbaseide/slashbase/pull/60
