### ISSUE TITLE
Update contributing guidelines.

### ISSUE THREAD

**Issue by dozheiny** [slashbaseide/slashbase#59]
Please update your contributing guidelines.
There are some issues with the current guidelines.
In the [section](https://github.com/slashbaseide/slashbase/blob/main/CONTRIBUTING.md#setup-development-environment) on setting up the development environment, it is stated that the file at development.env.sample should be copied and pasted as development.env in the root directory of the project. However, in this [section](https://slashbase.bip.wiki/contributing-34263c) on configuring the .env.local file, additional information is provided about updating email and password in the frontend package.
Additionally, in the [section](https://slashbase.bip.wiki/contributing-34263c) on running the project, it is stated that the project will listen on ports 3000 and 3001, but in reality, it only listens on port 22022. Thank you.

**Comment by paraswaykole** [comment]
Sorry! the environment has been changing very frequently for past couple of weeks. Will update contributing.md file to current environment asap.

**Comment by dozheiny** [comment]
Thanks.

**Comment by paraswaykole** [comment]
@dozheiny I have updated [slashbase.bip.wiki](https://slashbase.bip.wiki/contributing-34263c) and [CONTRIBUTING.md](https://github.com/slashbaseide/slashbase/blob/main/CONTRIBUTING.md#setup-development-environment) to latest dev environment.

Closing this issue.
