### ISSUE TITLE
UI improvement suggestion - Allow users to toggle view DB password

### ISSUE THREAD

**Issue by prashantkhandelwal** [slashbaseide/slashbase#61]
In the view, where user adds a new database connection, it will be good to have the ability to toggle the database password field.

Something like [this]( https://medium.com/@codefoxx/html-css-javascript-how-to-show-hide-password-using-the-eye-icon-27f033bf84ad) will be nice.

**Comment by sanyamjain04** [comment]
Can you please assign this issue to me ?
