### ISSUE TITLE
Incorrect docs

### ISSUE THREAD

**Issue by vichle** [slashbaseide/slashbase#7]
Hello!

First of all, it would be great if the docs were editable on Github, either in this repo or another, then this would be a PR instead of an issue. :smile: 

The URL to the wget command is incorrect, it says `slashbase/slashbase` instead of `slashbaseide/slashbase`
![image](https://user-images.githubusercontent.com/1671203/200655651-304a03c0-90d7-481d-b1a4-6a768d41358f.png)

**Comment by paraswaykole** [comment]
Thanks @vichle for pointing out. The url is fixed in the docs.
