### ISSUE TITLE
Console doesn't scroll properly to the bottom

### ISSUE THREAD

**Issue by paraswaykole** [slashbaseide/slashbase#95]
After a command is entered in the console and the commands results in a large table as output, the console displays the output but doesn't scroll properly to the bottom of the console.

**Comment by nc1337** [comment]
Hi @paraswaykole, I am using arch to reproduce the same issue in Arch, but i am unable too. The only issue which i am facing is the `vertical scrollbar` is `overlapping` and `horizontal` one is not visible. Kindly let me know if this is the issue.

**Comment by paraswaykole** [comment]
> The only issue which i am facing is the `vertical scrollbar` is `overlapping` and `horizontal` one is not visible. Kindly let me know if this is the issue.

No. It's not same. Seems like a different issue.

**Comment by paraswaykole** [comment]
Commit a6575dc591dfe9ae420dfe2b06445a8db0cac971 closes this issue
