### ISSUE TITLE
Make input field border red if it is empty while creating new database connection

### ISSUE THREAD

**Issue by RjPatil27** [slashbaseide/slashbase#96]
### One minor issue I found while adding a new database connection is, If any field is kept empty, it does show "cannot be empty," which is good.
We can make the border of the empty field Red if it is empty. (Warning)

![connectionForm](https://user-images.githubusercontent.com/30958676/225047826-9ccea06a-53c9-4193-ae32-190101ca9038.jpg)

**Comment by tarunsamanta2k20** [comment]
I am working on this issue.
